class BinarySearchTree:
    class _Node:
        def __init__(self, value, left: None, right: None):
            self.value = value
            self.left = left
            self.right = right

    def __init__(self):
        self.root = None

    def insert(self, value): ...

    def delete(self, value): ...

    def search(self, value): ...

    def contains(self, value) -> bool: ...

    def find_min(self): ...

    def find_max(self): ...

    def inorder_traversal(self): ...

    def preorder_traversal(self): ...

    def postorder_traversal(self): ...

    def height(self) -> int: ...

    def size(self) -> int: ...

    def is_empty(self) -> bool: ...

    def clear(self): ...
